version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    ports:
    - 8080:8080
    environment:
      - SERVER_PORT=8080
    volumes:
    - .:/app/
